### ISSUE TITLE
Can we get currency for certain amounts of XP or boss kills?

### ISSUE THREAD

**Issue by farhan1666** [CWorldEnder/personalcurrencytracker#1]

**Comment by CWorldEnder** [comment]
Hey, sorry for the delayed response. I have been thinking about the XP idea as well, and the boss kills sound like a nice idea too! I am currently kind of busy, but I will look into this as soon as I can! :)

**Comment by CWorldEnder** [comment]
I have implemented both and made a pull request in the plugin hub repo (runelite/plugin-hub#3411). The update will be in the plugin hub once they accept it. 👍

**Comment by CWorldEnder** [comment]
The pull request has been merged :)

Btw, I couldn't think of a simple way to make the Boss kill thing general enough without making a whole UI, so it is implemented as a text field where you type in the NPC names with their kill reward as such: `goblin#1, lynx tamer#6`. If you have a different idea, let me know and I can look into it :)
